# Generated by Django 6.0.5 on 2026-08-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_add_accepted_offer_declined_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="employer_name_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_location_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_title_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="jobs.job",
            ),
        ),
    ]
