# Generated by Django 6.0.5 on 2026-08-13 04:26

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    """Carry the old boolean over, so answered enquiries do not reappear as new."""
    ContactSubmission = apps.get_model("contact", "ContactSubmission")
    ContactSubmission.objects.filter(is_responded=True).update(status="replied")


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("read", "Read"), ("replied", "Replied")],
                default="new",
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
