# Generated by Django 6.0.5 on 2026-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_avatar_bio_location_to_physician_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="jobs_posted_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
