# Generated by Django 6.0.5 on 2026-08-06 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_add_revoked_reason_to_enterprise_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="annual_discount_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Percent off when paying yearly. 0 hides the annual option.",
                validators=[django.core.validators.MaxValueValidator(90)],
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_price_id_annual",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
