# Generated by Django 6.0.5 on 2026-08-11 03:31

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    """Follow STRIPE_CURRENCY instead of the hard-coded 'usd' default.

    Only the default changes. Existing rows keep the currency they were
    written with on purpose — a PaymentHistory row is a record of what a
    customer was actually charged, and rewriting it to today's currency would
    make the books say something that never happened.
    """

    dependencies = [
        ("subscriptions", "0008_subscriptionplan_annual_discount_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="currency",
            field=models.CharField(
                default=subscriptions.models.default_currency, max_length=10
            ),
        ),
    ]
